---
name: Deploy docker container

on:
  push:
    tags:
      - 'v*

jobs:
  deploy_docker:
    name: Docker deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Get metadata
        uses: docker/metadata-action@v4.1.1
        id: metadata
        with:
          images: ${{ github.repository }}

      - name: Login to Dockerhub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: . 
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}