---
name: Release package
on:
  workflow_dispatch:
    inputs:
      comments:
        description: Comments
        required: false
jobs:
  release_package:
    uses: khanlab/actions/.github/workflows/release/gh_release.yml@main
    with:
      comments: ${{ github.event.inputs.comments }}
      pipeline_description: true
    secrets:
      BP_PAT: ${{ secrets.BP_PAT_TOKEN }}
